# Generated by Django 5.1.2 on 2024-11-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='user',
            name='is_calibrated',
            field=models.BooleanField(default=False, verbose_name='Пройдена ли калибровка'),
        ),
    ]
