# Generated by Django 5.1.2 on 2024-12-02 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_mediatype_alter_watchlist_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MediaType',
        ),
    ]
