# Generated by Django 5.1.2 on 2024-11-24 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.CharField(max_length=255)),
                ('picture', models.ImageField(null=True, upload_to='', verbose_name='Изображение')),
                ('icon', models.ImageField(null=True, upload_to='', verbose_name='Иконка')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Подпись в карточке')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Тип медиа',
                'verbose_name_plural': 'Типы медиа',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpid', models.IntegerField(unique=True, verbose_name='ID Кинопоиск')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('movie_type', models.CharField(max_length=255, verbose_name='Тип')),
                ('ratingIMDB', models.FloatField(blank=True, verbose_name='Рейтинг IMDB')),
                ('ratingKP', models.FloatField(blank=True, verbose_name='Рейтинг Кинопоиск')),
                ('year', models.CharField(blank=True, max_length=4, verbose_name='Год выпуска')),
                ('ageRating', models.CharField(blank=True, max_length=3, verbose_name='Возрастной рейтинг')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('backdropURL', models.URLField(blank=True, verbose_name='Фон')),
                ('posterURL', models.URLField(blank=True, verbose_name='Постер')),
                ('trailerURL', models.URLField(blank=True, verbose_name='Ссылка на трейлер')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpid', models.IntegerField()),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('enName', models.CharField(max_length=255, verbose_name='Имя на англ.')),
                ('photoURL', models.URLField(verbose_name='Ссылка на фото')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('movie_kpid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie', to_field='kpid', verbose_name='ID фильма на кинопоиске')),
            ],
            options={
                'verbose_name': 'Актер фильма',
                'verbose_name_plural': 'Актеры фильмов',
            },
        ),
        migrations.CreateModel(
            name='MoviesCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255, verbose_name='Страна производства')),
                ('kpid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie', to_field='kpid', verbose_name='ID на кинопоиске')),
            ],
            options={
                'verbose_name': 'Страна производства фильма',
                'verbose_name_plural': 'Страны производства фильмов',
            },
        ),
        migrations.CreateModel(
            name='MoviesGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=255, verbose_name='Жанр')),
                ('kpid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie', to_field='kpid', verbose_name='ID фильма на кинопоиске')),
            ],
            options={
                'verbose_name': 'Жанр фильма',
                'verbose_name_plural': 'Жанры фильма',
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.URLField(blank=True, verbose_name='Ссылка')),
                ('kpid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movie', to_field='kpid')),
            ],
            options={
                'verbose_name': 'Скриншот',
                'verbose_name_plural': 'Скриншоты',
            },
        ),
        migrations.CreateModel(
            name='WatchabilityItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название сервиса')),
                ('logoURL', models.URLField(blank=True, verbose_name='Лого сервиса')),
                ('URL', models.URLField(blank=True, verbose_name='Ссылка')),
                ('kpid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie', to_field='kpid')),
            ],
            options={
                'verbose_name': 'Ссылка на сервис',
                'verbose_name_plural': 'Ссылки на сервисы',
            },
        ),
    ]
