# Generated by Django 5.1.2 on 2024-11-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='icon',
            field=models.ImageField(null=True, upload_to='static/movies/genre/icons', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='picture',
            field=models.ImageField(null=True, upload_to='static/movies/genre/pictures', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='subtitle',
            field=models.CharField(default=' ', max_length=255, verbose_name='Подпись в карточке'),
        ),
    ]
