# Generated by Django 5.1.2 on 2024-11-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_genre_icon_alter_genre_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='genre',
            name='icon',
            field=models.ImageField(null=True, upload_to='movies/genres/icons', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='picture',
            field=models.ImageField(null=True, upload_to='movies/genres/pictures', verbose_name='Изображение'),
        ),
    ]
