# Generated by Django 5.1.2 on 2024-12-01 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpid', models.IntegerField(unique=True, verbose_name='ID режиссера на КП')),
                ('name', models.CharField(max_length=255, verbose_name='Имя Фамилия')),
            ],
        ),
        migrations.AddField(
            model_name='genre',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='genre',
            name='subtitle',
            field=models.CharField(default=' ', max_length=255, null=True, verbose_name='Подпись в карточке'),
        ),
    ]
