# Generated by Django 5.1.2 on 2024-12-02 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_director_genre_is_main_alter_genre_subtitle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name': 'Режиссер', 'verbose_name_plural': 'Режиссеры'},
        ),
    ]
