# Generated by Django 5.1.2 on 2024-12-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_country_options_alter_director_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediatype',
            options={'verbose_name': 'Тип контента', 'verbose_name_plural': 'Типы контента'},
        ),
        migrations.AlterField(
            model_name='mediatype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='mediatype',
            name='slug',
            field=models.CharField(max_length=255),
        ),
    ]
