# Generated by Django 5.1.4 on 2024-12-09 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_mediatype_options_alter_mediatype_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_type',
            field=models.CharField(default=True, max_length=255, verbose_name='Тип'),
        ),
    ]
